spring.application.name=insumos

spring.datasource.url=jdbc:postgresql://localhost:5432/unisof_db
spring.datasource.username=postgres
spring.datasource.password=123456
# Esto hará que Hibernate cree las tablas automáticamente basadas en tu código Java
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true