# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy JAR app to Azure Web App - unisof-app

on:
  push:
    branches:
      - despliegue-azure
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4

    - name: Set up Java version
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build with Maven
      run: mvn clean package -DskipTests -B

    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v4
      with:
        name: java-app
        path: target/*.jar

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v4
      with:
        name: java-app

    - name: Login to Azure
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_DD43C42C0046401CBA435487C62ADB93 }}
        tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_9B23CBA6EBE94A798B9B31483E3FBAAA }}
        subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_27022CAC645B4D55AD7F8F7F16C38337 }}

    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v3
      with:
        app-name: 'unisof-app'
        slot-name: 'Production'
        package: '*.jar'
